# Generated by Django 3.1.1 on 2020-09-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='localizacao.regiao')),
            ],
        ),
    ]
