# Generated by Django 3.1.1 on 2020-09-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0003_auto_20200926_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiao',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
