# Generated by Django 3.1.1 on 2020-09-30 10:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0003_auto_20200926_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='posicao',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='posicao'),
        ),
    ]
